name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "srujanareddy" --password-stdin
        docker build -t srujanareddy/sports-betting-app:latest .
    - name: Push the Docker image to the repository
      run: docker push srujanareddy/sports-betting-app:latest